### ISSUE TITLE
Error: can't find file 'kemal'

### ISSUE THREAD

**Issue by Computershik73** [tmiland/Invidious-Updater#87] opened 2022-06-22 08:18 UTC
Invidious is ready to be installed, press any key to continue...

➜ Downloading Invidious from GitHub
Cloning into 'invidious'...
remote: Enumerating objects: 22859, done.
remote: Counting objects: 100% (708/708), done.
remote: Compressing objects: 100% (339/339), done.
remote: Total 22859 (delta 459), reused 600 (delta 369), pack-reused 22151
Receiving objects: 100% (22859/22859), 21.98 MiB | 4.54 MiB/s, done.
Resolving deltas: 100% (15119/15119), done.
channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
domain:
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
➜ Done
/home/invidious
Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
➜ Creating user kemal with password akZ6oWq98JnZN37lxfrsbpCdRUcNpCn6
CREATE ROLE
➜ Creating database invidious with owner kemal
CREATE DATABASE
➜ Grant all on database invidious to user kemal
GRANT
➜ Running /home/invidious/invidious/config/sql/annotations.sql
CREATE TABLE
GRANT
➜ Running /home/invidious/invidious/config/sql/channels.sql
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/channel_videos.sql
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/nonces.sql
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/playlists.sql
CREATE TYPE
CREATE TABLE
GRANT
➜ Running /home/invidious/invidious/config/sql/playlist_videos.sql
CREATE TABLE
GRANT
➜ Running /home/invidious/invidious/config/sql/session_ids.sql
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/users.sql
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/videos.sql
CREATE TABLE
GRANT
CREATE INDEX
✔ Finished Database section
➜ Updating config.yml with new info...
✔ Done.
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/crystal-loot/exception_page.git
Ignoring source of "backtracer" on shard.lock
Fetching https://github.com/Sija/backtracer.cr.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/iv-org/protodec.git
Fetching https://github.com/iv-org/lsquic.cr.git
Fetching https://github.com/athena-framework/negotiation.git
Outdated shard.lock (backtracer source changed). Please run shards update instead.
Showing last frame. Use --error-trace for full trace.

In src/invidious.cr:21:1

 21 | require "kemal"
      ^
Error: can't find file 'kemal'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?

✗ [ERROR] Build Process Failed!

 This is most likely an issue with Invidious, not this script!

➜ Report issue: https://github.com/iv-org/invidious/issues

**Comment by tmiland** [comment] 2022-08-03 07:14
Closing.
Not able to reproduce this issue on Debian 11 with latest [Master](https://raw.githubusercontent.com/tmiland/Invidious-Updater/master/invidious_update.sh)

**Closed by tmiland** 2022-08-03 07:14 UTC
